Added a PKGBUILD for other raspberries.
Added a unified PKGBUILD to install box86 on all RPi-based machines (that are fully supported by box86) and did some changes to README.md.

diff --git a/archlinux/PKGBUILD-raspberrypi b/archlinux/PKGBUILD-raspberrypi
--- a/archlinux/PKGBUILD-raspberrypi
+++ b/archlinux/PKGBUILD-raspberrypi
@@ -1,19 +1,19 @@
 # Maintainer: SpacingBat3 <youremail@domain.com>
 # Contributor: Sebastien Chevalier
-pkgname=box86-rpi4b-git
+pkgname=box86-rpi-git
 pkgver=r2798.0edc0374
 pkgrel=1
 pkgdesc="Linux Userspace x86 Emulator with a twist, targeted at ARM Linux devices."
 arch=('armv7h')
 url="https://github.com/ptitSeb/box86"
 license=('MIT')
-#depends=() # IDK dependencies of box86, I'll try provide them soon.
-#optdepends=('gl4es') # No need for that on RPi4B
+optdepends=('gl4es: OpenGL 2 for GLES 2 devices')
 makedepends=('git' 'cmake' 'make')
 provides=("${pkgname%-git}")
 conflicts=("${pkgname%-git}")
 source=('git+https://github.com/ptitSeb/box86')
 md5sums=('SKIP')
+_pimodel=`tr -d '\0' < /sys/firmware/devicetree/base/model`
 
 pkgver() {
 	cd "$srcdir/${pkgname%-git}"
@@ -22,10 +22,22 @@ pkgver() {
 
 prepare() {
 	cd "${srcdir}/${pkgname%-git}"
+	# Check for Pi version number
+	if [[ ${_pimodel} ~= "Raspberry Pi 4" ]]; then
+		_piversion=4
+	elif [[ ${_pimodel} ~= "Raspberry Pi 3" ]]; then
+		_piversion=3
+	elif [[ ${_pimodel} ~= "Raspberry Pi 2" ]]; then
+		_piversion=2
+	else
+		# Your RPI is not supported or this device is not a pi, cancel build then
+		echo -e "\033[01m\033[01;31m==> ERROR:\033[00;01m Your device is not supported! This script is for RPi model 4/3/2 (1/0 not supported).\033[00m"
+		exit 1
+	fi
+	echo -e "\033[01m\033[01;34m==> INFO:\033[00;01m Your detected Pi verion number is: \033[01;31m${_piversion}\033[01m.\033[00m"
 	if [[ ! -d ./build ]]; then
 		mkdir build && cd build
-		# Build for RPi4 only:
-		cmake .. -DRPI4=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
+		cmake .. -DRPI${_piversion}=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
 	fi
 }
 
@@ -33,9 +45,6 @@ build() {
 	cd "$srcdir/${pkgname%-git}/build"
 	make -j$(nproc)
 }
-
-# Unused right now:
-#check() {}
 
 package() {
 	cd "$srcdir/${pkgname%-git}/build"
