Updated the PKGBUILDS
Improved old PKGBUILDs and added the PKGBUILD for the RK3399 targets.

diff --git a/archlinux/PKGBUILD-pandora b/archlinux/PKGBUILD-pandora
--- a/archlinux/PKGBUILD-pandora
+++ b/archlinux/PKGBUILD-pandora
@@ -1,6 +1,7 @@
-# Maintainer: SpacingBat3 <youremail@domain.com>
-# Contributor: Sebastien Chevalier
+# Maintainer: SpacingBat3 <git@spacingbat3.anonaddy.com>
+# Contributor: Sebastien Chevalier <sebastien.chev@gmail.com>
 pkgname=box86-pandora-git
+_pkgname=box86-git
 pkgver=r2798.0edc0374
 pkgrel=1
 pkgdesc="Linux Userspace x86 Emulator with a twist, targeted at ARM Linux devices."
@@ -9,18 +10,18 @@ url="https://github.com/ptitSeb/box86"
 license=('MIT')
 optdepends=('gl4es: OpenGL 2 for GLES 2 devices')
 makedepends=('git' 'cmake' 'make')
-provides=("${pkgname%-git}")
-conflicts=("${pkgname%-git}")
+provides=("${pkgname%-git}" "${pkgname%-pandora-git}"-git "${pkgname%-pandora-git}")
+conflicts=("${pkgname%-git}" "${pkgname%-pandora-git}"-git "${pkgname%-pandora-git}")
 source=('git+https://github.com/ptitSeb/box86')
 md5sums=('SKIP')
 
 pkgver() {
-	cd "$srcdir/${pkgname%-git}"
+	cd "$srcdir/${pkgname%-pandora-git}"
 	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
 }
 
 prepare() {
-	cd "${srcdir}/${pkgname%-git}"
+	cd "${srcdir}/${pkgname%-pandora-git}"
 	if [[ ! -d ./build ]]; then
 		mkdir build && cd build
 		cmake .. -DPANDORA=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
@@ -28,11 +29,17 @@ prepare() {
 }
 
 build() {
-	cd "$srcdir/${pkgname%-git}/build"
+	cd "$srcdir/${pkgname%-pandora-git}/build"
 	make -j$(nproc)
 }
 
 package() {
 	cd "$srcdir/${pkgname%-git}/build"
 	make DESTDIR="${pkgdir}/" install
+	# /usr/local/bin isn't in PATH by the default,
+	# we should move it to /usr/bin
+	cd ${pkgdir}
+	mv usr/local/bin/ usr/bin/
+	# cleanup when dir is empty
+	rmdir usr/local || exit 0
 }
diff --git a/archlinux/PKGBUILD-raspberrypi b/archlinux/PKGBUILD-raspberrypi
--- a/archlinux/PKGBUILD-raspberrypi
+++ b/archlinux/PKGBUILD-raspberrypi
@@ -1,6 +1,7 @@
-# Maintainer: SpacingBat3 <youremail@domain.com>
-# Contributor: Sebastien Chevalier
+# Maintainer: SpacingBat3 <git@spacingbat3.anonaddy.com>
+# Contributor: Sebastien Chevalier <sebastien.chev@gmail.com>
 pkgname=box86-rpi-git
+_pkgname=box86-git
 pkgver=r2798.0edc0374
 pkgrel=1
 pkgdesc="Linux Userspace x86 Emulator with a twist, targeted at ARM Linux devices."
@@ -9,29 +10,30 @@ url="https://github.com/ptitSeb/box86"
 license=('MIT')
 optdepends=('gl4es: OpenGL 2 for GLES 2 devices')
 makedepends=('git' 'cmake' 'make')
-provides=("${pkgname%-git}")
-conflicts=("${pkgname%-git}")
+provides=("${pkgname%-git}" "${pkgname%-rpi-git}-git" "${pkgname%--rpi-git}")
+conflicts=("${pkgname%-git}" "${pkgname%-rpi-git}-git" "${pkgname%--rpi-git}")
 source=('git+https://github.com/ptitSeb/box86')
 md5sums=('SKIP')
 _pimodel=`tr -d '\0' < /sys/firmware/devicetree/base/model`
 
 pkgver() {
-	cd "$srcdir/${pkgname%-git}"
+	cd "$srcdir/${pkgname%-rpi-git}"
 	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
 }
 
 prepare() {
-	cd "${srcdir}/${pkgname%-git}"
+	cd "${srcdir}/${pkgname%-rpi-git}"
 	# Check for Pi version number
-	if [[ ${_pimodel} ~= "Raspberry Pi 4" ]]; then
+	if [[ ${_pimodel} =~ "Raspberry Pi 4" ]]; then
 		_piversion=4
-	elif [[ ${_pimodel} ~= "Raspberry Pi 3" ]]; then
+	elif [[ ${_pimodel} =~ "Raspberry Pi 3" ]]; then
 		_piversion=3
-	elif [[ ${_pimodel} ~= "Raspberry Pi 2" ]]; then
+	elif [[ ${_pimodel} =~ "Raspberry Pi 2" ]]; then
 		_piversion=2
 	else
-		# Your RPI is not supported or this device is not a pi, cancel build then
-		echo -e "\033[01m\033[01;31m==> ERROR:\033[00;01m Your device is not supported! This script is for RPi model 4/3/2 (1/0 not supported).\033[00m"
+		# This RPI is not supported or this device is not a pi.
+		# We should cancel then the build.
+		echo -e "\033[01m\033[01;31m==> ERROR:\033[00;01m Your device is not supported! This script is for RPi model 4/3/2 (1/0 isn't supported yet).\033[00m"
 		exit 1
 	fi
 	echo -e "\033[01m\033[01;34m==> INFO:\033[00;01m Your detected Pi verion number is: \033[01;31m${_piversion}\033[01m.\033[00m"
@@ -42,11 +44,17 @@ prepare() {
 }
 
 build() {
-	cd "$srcdir/${pkgname%-git}/build"
+	cd "$srcdir/${pkgname%-rpi-git}/build"
 	make -j$(nproc)
 }
 
 package() {
-	cd "$srcdir/${pkgname%-git}/build"
+	cd "$srcdir/${pkgname%-rpi-git}/build"
 	make DESTDIR="${pkgdir}/" install
+	# /usr/local/bin isn't in PATH by the default,
+	# we should move it to /usr/bin
+	cd ${pkgdir}
+	mv usr/local/bin/ usr/bin/
+	# cleanup when dir is empty
+	rmdir usr/local || exit 0
 }
diff --git a/archlinux/PKGBUILD-x86 b/archlinux/PKGBUILD-x86
--- a/archlinux/PKGBUILD-x86
+++ b/archlinux/PKGBUILD-x86
@@ -1,6 +1,7 @@
-# Maintainer: SpacingBat3 <youremail@domain.com>
-# Contributor: Sebastien Chevalier
+# Maintainer: SpacingBat3 <git@spacingbat3.anonaddy.com>
+# Contributor: Sebastien Chevalier <sebastien.chev@gmail.com>
 pkgname=box86-x86-git
+_pkgname=box86-git
 pkgver=r2798.0edc0374
 pkgrel=1
 pkgdesc="Linux Userspace x86 Emulator with a twist, targeted at ARM Linux devices."
@@ -8,18 +9,18 @@ arch=('i386')
 url="https://github.com/ptitSeb/box86"
 license=('MIT')
 makedepends=('git' 'cmake' 'make')
-provides=("${pkgname%-git}")
-conflicts=("${pkgname%-git}")
+provides=("${pkgname%-x86-git}")
+conflicts=("${pkgname%-x86-git}")
 source=('git+https://github.com/ptitSeb/box86')
 md5sums=('SKIP')
 
 pkgver() {
-	cd "$srcdir/${pkgname%-git}"
+	cd "$srcdir/${pkgname%-x86-git}"
 	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
 }
 
 prepare() {
-	cd "${srcdir}/${pkgname%-git}"
+	cd "${srcdir}/${pkgname%-x86-git}"
 	if [[ ! -d ./build ]]; then
 		mkdir build && cd build
 		cmake .. -DLD80BITS=1 -DNOALIGN=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
@@ -27,11 +28,17 @@ prepare() {
 }
 
 build() {
-	cd "$srcdir/${pkgname%-git}/build"
+	cd "$srcdir/${pkgname%-x86-git}/build"
 	make -j$(nproc)
 }
 
 package() {
-	cd "$srcdir/${pkgname%-git}/build"
+	cd "$srcdir/${pkgname%-x86-git}/build"
 	make DESTDIR="${pkgdir}/" install
+	# /usr/local/bin isn't in PATH by the default,
+	# we should move it to /usr/bin
+	cd ${pkgdir}
+	mv usr/local/bin/ usr/bin/
+	# cleanup when dir is empty
+	rmdir usr/local || exit 0
 }
